sudo: required

language: java

# Whitelist
branches:  
  only:
    - master

services:  
    # Enable docker service inside travis
    - docker

before_install:
    - docker pull ubuntu:16.04

install:
    # Build the spring boot app inside docker
    - docker run -v $(pwd):/root/build ubuntu:16.04 /bin/sh -c "cd /root/build; apt-get update; apt-get -y install openjdk-8-jdk maven; mvn -U -Dspring.profiles.active=test clean install;"
    # Copy the result to the docker folder
    - test -f target/mc-identityregistry-core-latest.war && cp target/mc-identityregistry-core-latest.war docker/ 


before_script:  
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
    # Build the docker image
    - docker build --no-cache -t dmadk/mc-identity-registry-api docker
    # Push the image to the repository
    - docker push dmadk/mc-identity-registry-api
