spring:
    profiles.active: development
---
spring:
    profiles: development
# Database setup
    datasource:
        url: jdbc:mysql://localhost/identity_registry
        username: idreg
        password: idreg
        driverClassName: com.mysql.jdbc.Driver

# SSL
server:
    port: 8443
    ssl:
        enabled: true
        # Keystore
        # key-store: classpath:keystore.jks
        key-store: mc-root-keystore.jks
        # key-store: /etc/ssl/certs/java/cacerts
        # key-alias: rootcert
        key-store-password: changeit
        key-password: changeit
        # Truststore
        trust-store: mc-truststore.jks
        trust-store-password: changeit
        client-auth: want

# Login info for the central keycloak MC ID broker (Used for ID Providers)
net:
    maritimecloud:
        idreg:
            keycloak-broker-admin-user: idreg-admin
            keycloak-broker-admin-password: idreg-admin
            keycloak-broker-admin-client: security-admin-console
            keycloak-broker-realm: master
            keycloak-broker-base-url: http://localhost:9080/auth/

            # Login info for the keycloak used for project users
            keycloak-project-users-admin-user: idreg-admin
            keycloak-project-users-admin-password: idreg-admin
            keycloak-project-users-admin-client: security-admin-console
            keycloak-project-users-realm: master
            keycloak-project-users-base-url: http://localhost:9080/auth/
---
spring:
    profiles: test
    datasource:
       url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
       driverClassName: org.h2.Driver
